# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python311:
      python.version: '3.11.10'

steps:
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python app/src/app.py &
  displayName: 'Running Webapp'

- script: |
    pip install pytest pytest-azurepipelines
    pytest app/test/test_sample.py
  displayName: 'pytest'

- script: |
      coverage run -m pytest
      coverage xml -o coverage.xml
  displayName: Generate coverage report

- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: '**/coverage.xml'

- script: |
    python setup.py bdist_wheel
  displayName: 'packaging the webapp'

- task: ArtifactoryGenericUpload@2
  inputs:
    artifactoryService: 'jfrogartifactory'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "dist/*",
            "target": "azdevops-pypi-local"
          }
        ]
      }
    failNoOp: true
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'jfrogartifactory'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

