# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python311:
      python.version: '3.11.10'

steps:
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python app.py &
  displayName: 'Running Webapp'

- script: |
    pip install pytest pytest-azurepipelines
    pytest test_sample.py
  displayName: 'pytest'

- script: |
      coverage run -m pytest
      coverage xml -o coverage.xml
  displayName: Generate coverage report

- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: '**/coverage.xml'
